### PR TITLE
added  methods writeToSRAM()/readFromSRAM() for writing/reading several bytes in one go

### PR DESCRIPTION
**Pull request by agrommek**
Hi Everybody,

Thank you for creating this great library!!! 

I added methods readFromSRAM() and writeToSRAM() which make it possible to read/write **several** bytes from/to SRAM into/from an array with a **single** function call and only two SPI transactions (instead of one SPI transaction for every byte). This is a bit faster and (arguably) more readable than looping over SRAM addresses in the main sketch.

writeToSRAM() takes a pointer to an array to get the values from and the number of values to write.

readFromSRAM() takes a pointer to an array where the values from SRAM are written to and the number of values.

Rationale: For a recent project, I needed to store several bytes from an array in SRAM and read them back later (in my case this was the timestamp of the synchronization with an external time source). Of course I could have used the existing methods and iterated over the SRAM address space in the main sketch - but as the DS3234 auto-increments the read read/write pointer during SPI transactions, why not read or write all bytes in a single go? Adding these methods made my sketch much more readable.

Hope you will accept this pull request.

Cheers

### CODE REVIEW

**Comment by nseidle** [comment]
Hi @agrommek - Thank you very much for the PR! I apologize for the slow reply. The PR looks fine. Would you mind adding an example that demonstrates the new functionality? This helps both me test it and future users easily implement it.

Please also re-base as main has progressed a bit.

**Comment by agrommek** [comment]
Hi @nseidle 

I just rebased my PR on your current master branch (hope I did everything correctly, I'm not so experienced using git...). 
Of course I can provide some examples. Would you like a separate example sketch for that or should I modify the existing demo sketch?

Please note, that I have currently no DS3234 module on by desk. However, I should have one around here somewhere. It may be a few days until I can write and test an example. Is this ok for you?

There is yet another matter: I have made some further additions to readToSRAM/writeToSRAM. In my personal version, there is now a templated version for those functions which allows other data types (float, uint32_t, ...) to be directly read from or written to SRAM. Please see here: https://github.com/agrommek/SparkFun_DS3234_RTC_Arduino_Library/blob/aa6b2169a0e03f9d911d0497d6e4e37166e38f56/src/SparkFunDS3234RTC.cpp#L698

Would you be interested to add this functionality as well? If yes, should I open a new PR or would you like me to add this to this PR?

**Comment by agrommek** [comment]
Hi @nseidle 

Found my RTC module and just added an example sketch to my PR.
Andreas

**Comment by nseidle** [comment]
Excellent - thank you! Looks very good. Merging.

**Pull request merged**
